version: "3"

services:
  app:
    image: uniontechdev/call-drop-node:0.0.2-patch
    ports:
      - "3000:3000"
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    ports:
      - "80:80"
      - "443:443"
